import { agentLabels, buildAgentKickoffPrompt, type AuthMethod, type StarterConfigV2 } from "./core.js";

export const STARTER_VERSION = "0.4.0";

export const dependencyVersions = {
  next: "16.3.1",
  react: "19.2.0",
  typescript: "6.0.3",
  tailwind: "4.3.3",
  baseUi: "^1.6.0",
  radix: "^1.6.7",
  biome: "2.2.4",
  eslint: "9.39.5",
  prettier: "^3.6.2",
  vitest: "^3.2.4",
  playwright: "^1.55.0",
  betterAuth: "^1.7.0",
  drizzle: "^0.45.2",
  drizzleKit: "^0.31.4",
  prisma: "^7.1.0",
  motion: "^13.1.0",
} as const;

export const skillBundle = [
  { source: "vercel/next.js", skill: "next-dev-loop", purpose: "Verify Next.js behavior in the running application." },
  { source: "vercel-labs/agent-skills", skill: "vercel-react-best-practices", purpose: "Review React rendering, data flow, and performance." },
  { source: "vercel-labs/agent-skills", skill: "vercel-composition-patterns", purpose: "Prefer maintainable component composition." },
  { source: "vercel-labs/agent-skills", skill: "web-design-guidelines", purpose: "Check accessibility and responsive interface quality." },
  { source: "microsoft/playwright-cli", skill: "playwright-cli", purpose: "Verify the product through a real browser." },
  { source: "forrestchang/andrej-karpathy-skills", skill: "karpathy-guidelines", purpose: "Keep changes simple, explicit, and verifiable." },
  { source: "leonxlnx/taste-skill", skill: "design-taste-frontend", purpose: "Apply quality, accessibility, responsiveness, and motion checks without restyling the selected reference." },
  { source: "getsentry/skills", skill: "security-review", purpose: "Review trust boundaries, secrets, and common security risks." },
] as const;

export function renderWorkflows(config: StarterConfigV2): Record<string, string> {
  const designInstruction = config.designReference ? " and DESIGN.md" : "";
  return {
    "implement-blueprint": `# Implement blueprint\n\nRead APP_BLUEPRINT.md${designInstruction}. Identify the smallest unimplemented vertical slice, plan it, implement it with tests, and run focused verification. Do not introduce unselected providers.`,
    verify: `# Verify\n\nRun the repository verify script. Verify changed behavior in a real browser when Playwright is selected, including keyboard access, mobile reflow, console errors, and reduced motion. Report exact commands and outcomes.`,
    review: `# Review\n\nReview the current diff for correctness, security, accessibility, responsive behavior, provider leakage, design-system drift, and missing tests. Lead with actionable findings and cite files and lines.`,
    "ship-check": `# Ship check\n\nConfirm the blueprint is implemented, environment variables are documented, migrations are safe, CI is green when selected, telemetry excludes sensitive data, the production build succeeds, and rollback is understood. Stop on unresolved high-risk findings.`,
  };
}

const authMethodLabels: Record<AuthMethod, string> = {
  "email-password": "Email and password",
  github: "GitHub",
  google: "Google",
  microsoft: "Microsoft",
};

export function renderBlueprint(config: StarterConfigV2): string {
  const designDetails = config.designReference && config.designSource
    ? `- Design reference: ${config.designReference}\n- Design source: ${config.designSource.repository}/${config.designSource.path}\n`
    : "- Design reference: None\n";
  const designContract = config.designReference
    ? "1. Treat this document and DESIGN.md as the source of truth."
    : "1. Treat this document as the source of truth.";
  const designPackageRule = config.designReference
    ? "\n7. Install and configure fonts or packages explicitly named by DESIGN.md from their original legal sources; do not silently substitute them."
    : "";
  const designSource = config.designReference ? "- Design guidance: [voltagent/awesome-design-md](https://github.com/voltagent/awesome-design-md) (copied unchanged from the pinned source)\n" : "";
  return `# Application Blueprint

Generated by @bishoymly/start v${STARTER_VERSION} from a portable blueprint.

## Project setup

- Project: ${config.projectName}
- Target folder: ${config.targetDirectory}
- Coding agents: ${[config.primaryAgent, ...config.additionalAgents].map((agent) => agentLabels[agent]).join(", ")}
- Package manager: ${config.packageManager}
- Tooling: ${config.tooling}
- Code host: ${config.codeHost}
- Hosting: ${config.hosting}

## UI layer

- UI baseline: Tailwind CSS and shadcn/ui with ${config.uiFoundation === "base-ui" ? "Base UI" : "Radix UI"}
- shadcn preset: ${config.shadcnPreset.code} (${config.shadcnPreset.style}, ${config.shadcnPreset.theme}, ${config.shadcnPreset.font}, ${config.shadcnPreset.radius} radius)
- Starting surface: ${config.startingSurface}
${designDetails.trimEnd()}
- Theme: ${config.theme}${config.themeAdapted ? " (implementation adaptation; do not rewrite DESIGN.md)" : ""}
- Motion: ${config.motion}

## Auth and services

- Authentication: ${config.authentication}
- Sign-in methods: ${config.authMethods.map((method) => authMethodLabels[method]).join(", ") || "None"}
- Database: ${config.databaseRequired ? `${config.databaseProvider} with ${config.orm}` : "None"}
- Storage: ${config.storage}
- AI providers through Vercel AI SDK: ${config.aiProviders.join(", ") || "None"}

## Delivery

- CI: ${config.ciEnabled ? config.ci : "Not generated"}
- Testing: ${config.testing.join(", ") || "None"}
- Observability: ${config.observability.join(", ") || "None"}

## Implementation contract

${designContract}
2. Keep provider code behind narrow adapters; do not add providers that were not selected.
3. Keep secrets server-only and document every required environment variable.
4. Authorize protected work inside server-side data access and mutation functions; proxy redirects are not authorization.
5. Make each change small enough to verify. Run ${config.packageManager} run verify before shipping.
6. Preserve human control for destructive or externally visible agent actions.${designPackageRule}

## Sources

${designSource}- Next.js runtime guidance: [vercel/next.js](https://github.com/vercel/next.js)
- UI primitives: [shadcn/ui](https://github.com/shadcn-ui/ui)
- Browser verification: [microsoft/playwright](https://github.com/microsoft/playwright)
`;
}

export function renderDesign(markdown: string): string {
  return markdown;
}

export function renderAgents(config: StarterConfigV2): string {
  const designDocument = config.designReference ? " and DESIGN.md" : "";
  const designRule = config.designReference ? "- Treat the upstream DESIGN.md as written. Keep its named fonts, packages, and implementation guidance.\n" : "";
  return `# Repository instructions

Read APP_BLUEPRINT.md${designDocument} before planning or editing.

## Build loop

1. State the intended outcome and affected files.
2. Inspect the current implementation and its tests.
3. Implement the smallest coherent change.
4. Run focused checks, then \`${config.packageManager} run verify\`.
5. Report evidence, remaining risks, and skipped verification.

## Product rules

- Use only the selected providers in APP_BLUEPRINT.md.
${designRule}- Build with Tailwind CSS and the generated shadcn/ui source components.
- Accessibility, responsive behavior, reduced motion, and clear focus remain requirements.
- Do not expose secrets to Client Components or browser bundles.
- Check authentication and authorization inside every protected Server Component, Server Action, and Route Handler.
- Ask before destructive changes, production mutations, or external messages.

## Motion

- Level: ${config.motion}.
- ${config.motion === "off" ? "Do not add the Motion dependency." : "Import from motion/react and keep animation in leaf Client Components."}
- No GSAP or scroll hijacking.
`;
}

export function renderSkillsLock(): string {
  return JSON.stringify({ schemaVersion: 1, installedBy: `@bishoymly/start@${STARTER_VERSION}`, skills: skillBundle }, null, 2) + "\n";
}

type PackageManifest = {
  name: string;
  version: string;
  private: true;
  packageManager: string;
  scripts: Record<string, string>;
  dependencies: Record<string, string>;
  devDependencies: Record<string, string>;
};

const packageManagerVersions: Record<StarterConfigV2["packageManager"], string> = {
  npm: "npm@11.6.0",
  pnpm: "pnpm@10.17.1",
  yarn: "yarn@4.9.4",
  bun: "bun@1.2.22",
};

export function createPackageManifest(config: StarterConfigV2): PackageManifest {
  const dependencies: Record<string, string> = {
    next: dependencyVersions.next,
    react: dependencyVersions.react,
    "react-dom": dependencyVersions.react,
    "class-variance-authority": "^0.7.1",
    clsx: "^2.1.1",
    "tailwind-merge": "^3.6.0",
  };
  dependencies[config.uiFoundation === "base-ui" ? "@base-ui/react" : "radix-ui"] = config.uiFoundation === "base-ui" ? dependencyVersions.baseUi : dependencyVersions.radix;
  if (config.motion !== "off") dependencies.motion = dependencyVersions.motion;
  if (config.authentication === "better-auth") dependencies["better-auth"] = dependencyVersions.betterAuth;
  if (config.databaseRequired) {
    if (config.orm === "drizzle") {
      dependencies["drizzle-orm"] = dependencyVersions.drizzle;
      if (config.databaseProvider === "neon") dependencies["@neondatabase/serverless"] = "^1.0.2";
      else if (config.databaseProvider === "supabase") dependencies.postgres = "^3.4.7";
      else dependencies.pg = "^8.16.3";
    } else {
      dependencies["@prisma/client"] = dependencyVersions.prisma;
      dependencies["@prisma/adapter-pg"] = dependencyVersions.prisma;
      dependencies.pg = "^8.16.3";
    }
  }
  if (config.storage === "vercel-blob") dependencies["@vercel/blob"] = "^2.0.0";
  if (["s3", "r2"].includes(config.storage)) dependencies["@aws-sdk/client-s3"] = "^3.890.0";
  if (config.storage === "azure-blob") dependencies["@azure/storage-blob"] = "^12.28.0";
  if (config.storage === "gcs") dependencies["@google-cloud/storage"] = "^7.17.0";
  if (config.storage === "supabase-storage") dependencies["@supabase/supabase-js"] = "^2.57.0";
  if (config.aiProviders.length) dependencies.ai = "^5.0.0";
  const aiPackages: Partial<Record<StarterConfigV2["aiProviders"][number], string>> = { openai: "@ai-sdk/openai", anthropic: "@ai-sdk/anthropic", google: "@ai-sdk/google", "azure-openai": "@ai-sdk/azure", bedrock: "@ai-sdk/amazon-bedrock", vertex: "@ai-sdk/google-vertex", "vercel-ai-gateway": "@ai-sdk/gateway" };
  config.aiProviders.forEach((provider) => { if (aiPackages[provider]) dependencies[aiPackages[provider] as string] = "^2.0.0"; });
  if (config.observability.includes("opentelemetry")) dependencies["@vercel/otel"] = "^1.13.0";
  if (config.observability.includes("sentry")) dependencies["@sentry/nextjs"] = "^10.10.0";

  const devDependencies: Record<string, string> = {
    "@tailwindcss/postcss": dependencyVersions.tailwind,
    "@types/node": "^24.5.0",
    "@types/react": "^19.1.13",
    "@types/react-dom": "^19.1.9",
    postcss: "^8.5.6",
    tailwindcss: dependencyVersions.tailwind,
    typescript: dependencyVersions.typescript,
  };
  if (config.tooling === "biome") devDependencies["@biomejs/biome"] = dependencyVersions.biome;
  else Object.assign(devDependencies, { eslint: dependencyVersions.eslint, "eslint-config-next": dependencyVersions.next, "eslint-config-prettier": "^10.1.8", prettier: dependencyVersions.prettier });
  if (config.testing.includes("vitest")) Object.assign(devDependencies, { vitest: dependencyVersions.vitest, vite: "^7.1.7", "@vitejs/plugin-react": "^5.0.4", jsdom: "^27.0.0", "@testing-library/react": "^16.3.0", "@testing-library/jest-dom": "6.9.1" });
  if (config.testing.includes("playwright")) devDependencies["@playwright/test"] = dependencyVersions.playwright;
  if (config.orm === "drizzle") Object.assign(devDependencies, { "drizzle-kit": dependencyVersions.drizzleKit, dotenv: "^17.2.2", ...(config.databaseProvider !== "neon" && config.databaseProvider !== "supabase" ? { "@types/pg": "^8.15.5" } : {}) });
  if (config.orm === "prisma") Object.assign(devDependencies, { prisma: dependencyVersions.prisma, dotenv: "^17.2.2", "@types/pg": "^8.15.5" });

  const run = `${config.packageManager} run`;
  const scripts: Record<string, string> = { dev: "next dev", build: "next build", start: "next start", typecheck: "tsc --noEmit" };
  if (config.tooling === "biome") Object.assign(scripts, { lint: "biome lint .", "lint:fix": "biome lint --write .", format: "biome format --write .", "format:check": "biome format ." });
  else Object.assign(scripts, { lint: "eslint .", "lint:fix": "eslint . --fix", format: "prettier --write .", "format:check": "prettier --check ." });
  if (config.testing.includes("vitest")) Object.assign(scripts, { test: "vitest run", "test:watch": "vitest" });
  if (config.testing.includes("playwright")) Object.assign(scripts, { "test:e2e:install": "playwright install chromium", "test:e2e": "playwright test", "test:e2e:ui": "playwright test --ui" });
  if (config.orm === "drizzle") Object.assign(scripts, { "db:generate": "drizzle-kit generate", "db:migrate": "drizzle-kit migrate", "db:push": "drizzle-kit push", "db:studio": "drizzle-kit studio" });
  if (config.orm === "prisma") Object.assign(scripts, { postinstall: "prisma generate", "db:generate": "prisma generate", "db:migrate": "prisma migrate dev", "db:deploy": "prisma migrate deploy", "db:studio": "prisma studio" });
  if (config.authentication === "better-auth") scripts["auth:schema"] = "auth generate --config ./lib/auth.ts --yes";
  const verify = [`${run} lint`, `${run} format:check`, `${run} typecheck`];
  if (config.testing.includes("vitest")) verify.push(`${run} test`);
  if (config.testing.includes("playwright")) verify.push(`${run} test:e2e`);
  verify.push(`${run} build`);
  scripts.verify = verify.join(" && ");
  return { name: config.projectName, version: "0.1.0", private: true, packageManager: packageManagerVersions[config.packageManager], scripts, dependencies, devDependencies };
}

export function renderPackageJson(config: StarterConfigV2): string {
  return JSON.stringify(createPackageManifest(config), null, 2) + "\n";
}

export type EnvironmentVariable = { name: string; description: string; required: boolean };

export function environmentVariables(config: StarterConfigV2): EnvironmentVariable[] {
  const variables: EnvironmentVariable[] = [];
  const add = (name: string, description: string, required = true) => variables.push({ name, description, required });
  if (config.databaseRequired) {
    add("DATABASE_URL", "Runtime PostgreSQL connection string.");
    if (["neon", "supabase"].includes(config.databaseProvider ?? "")) add("DIRECT_URL", "Direct PostgreSQL connection used by migration tooling.");
  }
  if (config.authentication === "better-auth") {
    add("BETTER_AUTH_SECRET", "At least 32 random characters used to sign authentication data.");
    add("BETTER_AUTH_URL", "Canonical application URL, such as http://localhost:3000.");
    if (config.authMethods.includes("github")) { add("GITHUB_CLIENT_ID", "GitHub OAuth application client ID."); add("GITHUB_CLIENT_SECRET", "GitHub OAuth application client secret."); }
    if (config.authMethods.includes("google")) { add("GOOGLE_CLIENT_ID", "Google OAuth web client ID."); add("GOOGLE_CLIENT_SECRET", "Google OAuth client secret."); }
    if (config.authMethods.includes("microsoft")) { add("MICROSOFT_CLIENT_ID", "Microsoft Entra application client ID."); add("MICROSOFT_CLIENT_SECRET", "Microsoft Entra application client secret."); add("MICROSOFT_TENANT_ID", "Microsoft tenant ID; use common for multi-tenant sign-in.", false); }
  }
  const storage: Partial<Record<StarterConfigV2["storage"], [string, string][]>> = {
    "vercel-blob": [["BLOB_READ_WRITE_TOKEN", "Vercel Blob read/write token."]],
    s3: [["AWS_ACCESS_KEY_ID", "AWS access key."], ["AWS_SECRET_ACCESS_KEY", "AWS secret key."], ["AWS_REGION", "AWS region."]],
    r2: [["R2_ACCOUNT_ID", "Cloudflare account ID."], ["R2_ACCESS_KEY_ID", "R2 access key."], ["R2_SECRET_ACCESS_KEY", "R2 secret key."]],
    "azure-blob": [["AZURE_STORAGE_CONNECTION_STRING", "Azure Blob Storage connection string."]],
    gcs: [["GOOGLE_APPLICATION_CREDENTIALS", "Path to Google service-account credentials."]],
    "supabase-storage": [["NEXT_PUBLIC_SUPABASE_URL", "Public Supabase project URL."], ["SUPABASE_SERVICE_ROLE_KEY", "Server-only Supabase service role key."]],
  };
  (storage[config.storage] ?? []).forEach(([name, description]) => add(name, description));
  const ai: Partial<Record<StarterConfigV2["aiProviders"][number], [string, string][]>> = {
    openai: [["OPENAI_API_KEY", "OpenAI API key."]], anthropic: [["ANTHROPIC_API_KEY", "Anthropic API key."]], google: [["GOOGLE_GENERATIVE_AI_API_KEY", "Google Generative AI key."]], "azure-openai": [["AZURE_OPENAI_API_KEY", "Azure OpenAI API key."], ["AZURE_OPENAI_ENDPOINT", "Azure OpenAI endpoint."]], bedrock: [["AWS_ACCESS_KEY_ID", "AWS access key."], ["AWS_SECRET_ACCESS_KEY", "AWS secret key."], ["AWS_REGION", "AWS region."]], vertex: [["GOOGLE_VERTEX_PROJECT", "Google Cloud project ID."], ["GOOGLE_VERTEX_LOCATION", "Google Vertex region."]], "vercel-ai-gateway": [["AI_GATEWAY_API_KEY", "Vercel AI Gateway API key."]],
  };
  config.aiProviders.forEach((provider) => (ai[provider] ?? []).forEach(([name, description]) => add(name, description)));
  if (config.observability.includes("opentelemetry")) add("OTEL_EXPORTER_OTLP_ENDPOINT", "Optional OTLP collector endpoint.", false);
  if (config.observability.includes("sentry")) { add("SENTRY_ORG", "Sentry organization slug used for source-map uploads."); add("SENTRY_PROJECT", "Sentry project slug used for source-map uploads."); add("SENTRY_AUTH_TOKEN", "Server-only Sentry build and source-map token."); add("NEXT_PUBLIC_SENTRY_DSN", "Public Sentry DSN."); }
  return [...new Map(variables.map((variable) => [variable.name, variable])).values()];
}

export function renderEnvExample(config: StarterConfigV2): string {
  const variables = environmentVariables(config);
  if (!variables.length) return "# No environment variables are required by the selected blueprint.\n";
  return ["# Copy this file to .env.local. Never commit real secrets.", ...variables.flatMap((variable) => [`\n# ${variable.description}${variable.required ? "" : " Optional."}`, `${variable.name}=${variable.name === "BETTER_AUTH_URL" ? "http://localhost:3000" : variable.name === "MICROSOFT_TENANT_ID" ? "common" : ""}`])].join("\n") + "\n";
}

function command(config: StarterConfigV2, executable: string): string {
  return config.packageManager === "npm" ? `npm run ${executable}` : `${config.packageManager} ${executable}`;
}

export function renderReadme(config: StarterConfigV2): string {
  const env = environmentVariables(config);
  const selectedAgents = [config.primaryAgent, ...config.additionalAgents].map((agent) => agentLabels[agent]).join(", ");
  const envTable = env.length ? `| Variable | Required | Purpose |\n| --- | --- | --- |\n${env.map((item) => `| \`${item.name}\` | ${item.required ? "Yes" : "No"} | ${item.description} |`).join("\n")}` : "This blueprint does not require environment variables.";
  const oauthCallbacks = config.authMethods.filter((method) => method !== "email-password").map((method) => `- ${authMethodLabels[method]}: \`\${BETTER_AUTH_URL}/api/auth/callback/${method}\``).join("\n");
  const auth = config.authentication === "better-auth" ? `\n## Authentication\n\nBetter Auth is configured with ${config.authMethods.map((method) => authMethodLabels[method]).join(", ")}. The API handler, sign-in experience, protected dashboard, and server-side session guard are included. The proxy performs an early redirect only; protected server code must call the session guard.\n${oauthCallbacks ? `\nRegister these callback URLs with the selected OAuth applications:\n\n${oauthCallbacks}\n` : ""}\nRun \`${command(config, "auth:schema")}\` after changing Better Auth plugins or auth fields, review the generated schema, then apply it with the ORM migration command.\n` : "";
  const database = config.databaseRequired ? `\n## Database\n\n${config.orm === "drizzle" ? `Use \`${command(config, "db:generate")}\` to create migrations and \`${command(config, "db:migrate")}\` to apply them.` : `Use \`${command(config, "db:migrate")}\` during development and \`${command(config, "db:deploy")}\` during deployment.`} The schema contains only infrastructure required by the selected services; add product models when the product needs them.\n` : "";
  const agentInstructions = config.designReference
    ? "1. `APP_BLUEPRINT.md` records the selected stack and implementation contract.\n2. `DESIGN.md` is the unchanged, provenance-pinned design reference.\n3. `AGENTS.md` defines the shared repository workflow and safety rules.\n4. Native agent files point Codex, Claude Code, Cursor, and other selected tools back to those shared sources.\n5. `.agents/commands/` contains portable implement, verify, review, and ship-check workflows."
    : "1. `APP_BLUEPRINT.md` records the selected stack and implementation contract.\n2. `AGENTS.md` defines the shared repository workflow and safety rules.\n3. Native agent files point Codex, Claude Code, Cursor, and other selected tools back to those shared sources.\n4. `.agents/commands/` contains portable implement, verify, review, and ship-check workflows.";
  const startingPoint = config.designReference ? "the blueprint and design reference" : "the blueprint";
  return `# ${config.projectName}

An agent-ready Next.js workspace generated from a focused Start blueprint.

## What was generated

- Next.js ${dependencyVersions.next}, React, strict TypeScript, Tailwind CSS, and shadcn/ui with ${config.uiFoundation === "base-ui" ? "Base UI" : "Radix UI"}
- ${config.tooling === "biome" ? "Biome for linting and formatting" : "ESLint with Next.js rules and Prettier"}
- ${config.testing.length ? config.testing.join(" and ") : "No test runner"}
- ${config.ciEnabled ? config.ci : "No CI workflow"}
- ${config.observability.length ? config.observability.join(" and ") : "No observability packages"}
- Agent instructions for ${selectedAgents}
- Starting surface: ${config.startingSurface}; shadcn preset: ${config.shadcnPreset.style}/${config.shadcnPreset.theme}

Only selected providers and tools are installed.

## Start locally

1. Copy \`.env.example\` to \`.env.local\` and fill the selected service values.
2. Install dependencies with \`${config.packageManager} install\`.
${config.databaseRequired ? `3. Apply the database schema with \`${command(config, "db:migrate")}\`.\n4. Start the app with \`${command(config, "dev")}\`.` : `3. Start the app with \`${command(config, "dev")}\`.`}

## Commands

- \`${command(config, "dev")}\` — run the development server
- \`${command(config, "verify")}\` — lint, check formatting, typecheck, run selected tests, and build
- \`${command(config, "lint:fix")}\` — apply safe lint fixes
- \`${command(config, "format")}\` — format the workspace
${config.testing.includes("vitest") ? `- \`${command(config, "test")}\` — run unit/component tests\n` : ""}${config.testing.includes("playwright") ? `- \`${command(config, "test:e2e:install")}\` — install the pinned Chromium browser\n- \`${command(config, "test:e2e")}\` — run browser tests\n` : ""}${database}${auth}
## Environment variables

${envTable}

## How agent instructions work

${agentInstructions}

## Agent kickoff

Copy this after generating the workspace:

> ${buildAgentKickoffPrompt(config)}

Start product work by reading ${startingPoint}, then ask your coding agent to run the implement-blueprint workflow for the smallest useful vertical slice.
`;
}

const shadcnButton = `import type * as React from "react";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "@/lib/utils";

const buttonVariants = cva("inline-flex h-10 items-center justify-center rounded-md px-4 text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50", { variants: { variant: { default: "bg-primary text-primary-foreground hover:bg-primary/90", outline: "border border-border bg-background hover:bg-accent", ghost: "hover:bg-accent" } }, defaultVariants: { variant: "default" } });

export function Button({ className, variant, ...props }: React.ComponentProps<"button"> & VariantProps<typeof buttonVariants>) { return <button className={cn(buttonVariants({ variant }), className)} {...props} />; }
`;

const shadcnFields = {
  "components/ui/input.tsx": `import type * as React from "react";\nimport { cn } from "@/lib/utils";\nexport function Input({ className, ...props }: React.ComponentProps<"input">) { return <input className={cn("h-10 w-full rounded-md border border-input bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:opacity-50", className)} {...props} />; }\n`,
  "components/ui/label.tsx": `import type * as React from "react";\nimport { cn } from "@/lib/utils";\nexport function Label({ className, ...props }: React.ComponentProps<"label">) { return <label className={cn("text-sm font-medium", className)} {...props} />; }\n`,
  "components/ui/card.tsx": `import type * as React from "react";\nimport { cn } from "@/lib/utils";\nexport function Card({ className, ...props }: React.ComponentProps<"section">) { return <section className={cn("rounded-lg border border-border bg-card text-card-foreground", className)} {...props} />; }\n`,
};

const presetFontImports: Record<StarterConfigV2["shadcnPreset"]["font"], string> = {
  inter: "Inter", "noto-sans": "Noto_Sans", "nunito-sans": "Nunito_Sans", figtree: "Figtree", roboto: "Roboto", raleway: "Raleway", "dm-sans": "DM_Sans", "public-sans": "Public_Sans", outfit: "Outfit", "jetbrains-mono": "JetBrains_Mono", geist: "Geist", "geist-mono": "Geist_Mono", lora: "Lora", merriweather: "Merriweather", "playfair-display": "Playfair_Display", "noto-serif": "Noto_Serif", "roboto-slab": "Roboto_Slab", oxanium: "Oxanium", manrope: "Manrope", "space-grotesk": "Space_Grotesk", montserrat: "Montserrat", "ibm-plex-sans": "IBM_Plex_Sans", "source-sans-3": "Source_Sans_3", "instrument-sans": "Instrument_Sans", "eb-garamond": "EB_Garamond", "instrument-serif": "Instrument_Serif",
};

const presetAccent: Record<StarterConfigV2["shadcnPreset"]["theme"], string> = {
  neutral: "oklch(0.46 0.02 265)", stone: "oklch(0.47 0.02 55)", zinc: "oklch(0.47 0.02 285)", gray: "oklch(0.48 0.03 260)", amber: "oklch(0.67 0.16 70)", blue: "oklch(0.58 0.19 255)", cyan: "oklch(0.66 0.13 210)", emerald: "oklch(0.60 0.14 165)", fuchsia: "oklch(0.60 0.22 320)", green: "oklch(0.59 0.16 145)", indigo: "oklch(0.55 0.20 275)", lime: "oklch(0.67 0.16 125)", orange: "oklch(0.64 0.19 45)", pink: "oklch(0.62 0.21 350)", purple: "oklch(0.56 0.21 300)", red: "oklch(0.60 0.21 25)", rose: "oklch(0.60 0.21 10)", sky: "oklch(0.64 0.15 235)", teal: "oklch(0.60 0.12 185)", violet: "oklch(0.57 0.21 290)", yellow: "oklch(0.76 0.16 90)", mauve: "oklch(0.52 0.04 320)", olive: "oklch(0.52 0.06 120)", mist: "oklch(0.54 0.04 210)", taupe: "oklch(0.52 0.04 55)",
};

const presetRadius: Record<StarterConfigV2["shadcnPreset"]["radius"], string> = { default: "0.625rem", none: "0rem", small: "0.375rem", medium: "0.625rem", large: "1rem" };

function renderFontSetup(config: StarterConfigV2): { imports: string; declarations: string; classes: string; headingCss: string } {
  const body = presetFontImports[config.shadcnPreset.font];
  const headingName = config.shadcnPreset.fontHeading === "inherit" ? null : presetFontImports[config.shadcnPreset.fontHeading];
  const names = [...new Set([body, "Geist_Mono", headingName].filter((item): item is string => Boolean(item)))];
  const imports = `import { ${names.join(", ")} } from "next/font/google";`;
  const options = (fontName: string, variable: string) => `{ subsets: ["latin"], variable: "${variable}"${fontName === "Instrument_Serif" ? `, weight: "400"` : ""} }`;
  const declarations = `const sans = ${body}(${options(body, "--font-preset-sans")});\nconst mono = Geist_Mono({ subsets: ["latin"], variable: "--font-preset-mono" });${headingName ? `\nconst heading = ${headingName}(${options(headingName, "--font-preset-heading")});` : ""}`;
  return { imports, declarations, classes: `\${sans.variable} \${mono.variable}${headingName ? " ${heading.variable}" : ""}`, headingCss: headingName ? `\nh1, h2, h3 { font-family: var(--font-preset-heading), var(--font-sans); }` : "" };
}

function renderHome(config: StarterConfigV2): string {
  const signIn = config.authentication === "better-auth" ? `<Link className="inline-flex h-10 items-center rounded-md border border-border bg-background px-4 text-sm font-medium hover:bg-accent" href="/sign-in">Sign in</Link>` : "";
  const sourceDocuments = config.designReference ? "APP_BLUEPRINT.md and DESIGN.md" : "APP_BLUEPRINT.md";
  const hero = `<section className="grid max-w-3xl gap-6"><p className="font-mono text-sm font-medium text-primary">Blueprint installed</p><h1 className="text-5xl font-semibold tracking-[-0.055em] sm:text-7xl">Ready to build ${config.projectName}.</h1><p className="max-w-2xl text-lg leading-relaxed text-muted-foreground">The selected UI foundation is in place. Read ${sourceDocuments}, then build the first real product slice.</p><div className="flex flex-wrap gap-3"><Button>Primary action</Button>${signIn}<Link className="inline-flex h-10 items-center font-medium text-primary underline underline-offset-4" href="https://bishoy.io/start">Adjust blueprint</Link></div></section>`;
  if (config.startingSurface === "minimal") return `import Link from "next/link";\nimport { Button } from "@/components/ui/button";\nexport default function Home() { return <main className="mx-auto grid min-h-dvh w-full max-w-5xl content-center px-6 py-20">${hero}</main>; }\n`;
  if (config.startingSurface === "top-nav") return `import Link from "next/link";\nimport { Button } from "@/components/ui/button";\nexport default function Home() { return <div className="min-h-dvh"><header className="border-b border-border"><div className="mx-auto flex h-16 w-full max-w-6xl items-center justify-between px-6"><Link className="font-semibold" href="/">${config.projectName}</Link><nav aria-label="Primary navigation" className="flex items-center gap-5 text-sm text-muted-foreground"><Link href="/">Overview</Link>${signIn}</nav></div></header><main className="mx-auto grid min-h-[calc(100dvh-4rem)] w-full max-w-6xl content-center px-6 py-20">${hero}</main></div>; }\n`;
  return `import Link from "next/link";\nimport { Button } from "@/components/ui/button";\nexport default function Home() { return <div className="min-h-dvh md:grid md:grid-cols-[15rem_1fr]"><aside className="border-b border-border bg-card px-6 py-5 md:min-h-dvh md:border-b-0 md:border-r"><Link className="font-semibold" href="/">${config.projectName}</Link><nav aria-label="Primary navigation" className="mt-6 flex gap-4 overflow-x-auto text-sm text-muted-foreground md:grid"><Link href="/">Overview</Link>${signIn}</nav></aside><main className="grid min-h-[calc(100dvh-5rem)] content-center px-6 py-20 md:min-h-dvh">${hero}</main></div>; }\n`;
}

function renderDatabaseFiles(config: StarterConfigV2): Record<string, string> {
  if (!config.databaseRequired || !config.orm) return {};
  const auth = config.authentication === "better-auth";
  if (config.orm === "drizzle") {
    const schema = auth ? `import { boolean, pgTable, text, timestamp } from "drizzle-orm/pg-core";

export const user = pgTable("user", { id: text("id").primaryKey(), name: text("name").notNull(), email: text("email").notNull().unique(), emailVerified: boolean("email_verified").default(false).notNull(), image: text("image"), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() });
export const session = pgTable("session", { id: text("id").primaryKey(), expiresAt: timestamp("expires_at").notNull(), token: text("token").notNull().unique(), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull(), ipAddress: text("ip_address"), userAgent: text("user_agent"), userId: text("user_id").notNull().references(() => user.id, { onDelete: "cascade" }) });
export const account = pgTable("account", { id: text("id").primaryKey(), accountId: text("account_id").notNull(), providerId: text("provider_id").notNull(), userId: text("user_id").notNull().references(() => user.id, { onDelete: "cascade" }), accessToken: text("access_token"), refreshToken: text("refresh_token"), idToken: text("id_token"), accessTokenExpiresAt: timestamp("access_token_expires_at"), refreshTokenExpiresAt: timestamp("refresh_token_expires_at"), scope: text("scope"), password: text("password"), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() });
export const verification = pgTable("verification", { id: text("id").primaryKey(), identifier: text("identifier").notNull(), value: text("value").notNull(), expiresAt: timestamp("expires_at").notNull(), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() });
` : `// Add product tables here when the application needs persistent domain data.\nexport {};\n`;
    const db = config.databaseProvider === "neon"
      ? `import { drizzle } from "drizzle-orm/neon-http";\nimport * as schema from "./schema";\nif (!process.env.DATABASE_URL) throw new Error("DATABASE_URL is required");\nexport const db = drizzle(process.env.DATABASE_URL, { schema });\n`
      : config.databaseProvider === "supabase"
        ? `import { drizzle } from "drizzle-orm/postgres-js";\nimport postgres from "postgres";\nimport * as schema from "./schema";\nif (!process.env.DATABASE_URL) throw new Error("DATABASE_URL is required");\nconst client = postgres(process.env.DATABASE_URL, { prepare: false });\nexport const db = drizzle(client, { schema });\n`
        : `import { drizzle } from "drizzle-orm/node-postgres";\nimport { Pool } from "pg";\nimport * as schema from "./schema";\nif (!process.env.DATABASE_URL) throw new Error("DATABASE_URL is required");\nconst pool = new Pool({ connectionString: process.env.DATABASE_URL });\nexport const db = drizzle({ client: pool, schema });\n`;
    return {
      "lib/db/index.ts": db,
      "lib/db/schema.ts": schema,
      "drizzle.config.ts": `import "dotenv/config";\nimport { defineConfig } from "drizzle-kit";\nconst url = process.env.${["neon", "supabase"].includes(config.databaseProvider ?? "") ? "DIRECT_URL ?? process.env.DATABASE_URL" : "DATABASE_URL"};\nif (!url) throw new Error("Database connection URL is required");\nexport default defineConfig({ schema: "./lib/db/schema.ts", out: "./drizzle", dialect: "postgresql", dbCredentials: { url } });\n`,
    };
  }
  const models = auth ? `
model User {
  id            String    @id
  name          String
  email         String    @unique
  emailVerified Boolean   @default(false)
  image         String?
  createdAt     DateTime  @default(now())
  updatedAt     DateTime  @updatedAt
  sessions      Session[]
  accounts      Account[]
}

model Session {
  id        String   @id
  expiresAt DateTime
  token     String   @unique
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  ipAddress String?
  userAgent String?
  userId    String
  user      User     @relation(fields: [userId], references: [id], onDelete: Cascade)
}

model Account {
  id                    String    @id
  accountId             String
  providerId            String
  userId                 String
  user                   User      @relation(fields: [userId], references: [id], onDelete: Cascade)
  accessToken            String?
  refreshToken           String?
  idToken                String?
  accessTokenExpiresAt   DateTime?
  refreshTokenExpiresAt  DateTime?
  scope                   String?
  password                String?
  createdAt               DateTime  @default(now())
  updatedAt               DateTime  @updatedAt
}

model Verification {
  id         String   @id
  identifier String
  value      String
  expiresAt  DateTime
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt
}
` : "\n// Add product models when the application needs persistent domain data.\n";
  return {
    "prisma/schema.prisma": `generator client {\n  provider = "prisma-client"\n  output   = "../lib/generated/prisma"\n}\n\ndatasource db {\n  provider = "postgresql"\n}\n${models}`,
    "prisma.config.ts": `import "dotenv/config";\nimport { defineConfig } from "prisma/config";\nconst connectionUrl = process.env.${["neon", "supabase"].includes(config.databaseProvider ?? "") ? "DIRECT_URL ?? process.env.DATABASE_URL" : "DATABASE_URL"};\nexport default defineConfig({ schema: "prisma/schema.prisma", migrations: { path: "prisma/migrations" }, ...(connectionUrl ? { datasource: { url: connectionUrl } } : {}) });\n`,
    "lib/db.ts": `import { PrismaPg } from "@prisma/adapter-pg";\nimport { PrismaClient } from "@/lib/generated/prisma/client";\nif (!process.env.DATABASE_URL) throw new Error("DATABASE_URL is required");\nconst globalForPrisma = globalThis as unknown as { prisma?: PrismaClient };\nconst adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });\nexport const db = globalForPrisma.prisma ?? new PrismaClient({ adapter });\nif (process.env.NODE_ENV !== "production") globalForPrisma.prisma = db;\n`,
  };
}

function renderAuthFiles(config: StarterConfigV2): Record<string, string> {
  if (config.authentication !== "better-auth") return {};
  const email = config.authMethods.includes("email-password");
  const socials = config.authMethods.filter((method): method is Exclude<AuthMethod, "email-password"> => method !== "email-password");
  const socialConfig = socials.map((provider) => `${provider}: { clientId: process.env.${provider.toUpperCase()}_CLIENT_ID as string, clientSecret: process.env.${provider.toUpperCase()}_CLIENT_SECRET as string${provider === "microsoft" ? ", tenantId: process.env.MICROSOFT_TENANT_ID ?? \"common\"" : ""} }`).join(",\n      ");
  const database = config.orm === "drizzle"
    ? `drizzleAdapter(db, { provider: "pg", schema })`
    : `prismaAdapter(db, { provider: "postgresql" })`;
  const imports = config.orm === "drizzle"
    ? `import { drizzleAdapter } from "better-auth/adapters/drizzle";\nimport { db } from "@/lib/db";\nimport * as schema from "@/lib/db/schema";`
    : `import { prismaAdapter } from "better-auth/adapters/prisma";\nimport { db } from "@/lib/db";`;
  const socialButtons = socials.map((provider) => `<Button type="button" variant="outline" onClick={() => void socialSignIn("${provider}")}>Continue with ${authMethodLabels[provider]}</Button>`).join("\n        ");
  const form = `"use client";
import { useId, useState, type FormEvent } from "react";
import { authClient } from "@/lib/auth-client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

export function SignInForm() {
  const [error, setError] = useState("");
  const emailId = useId();
  const passwordId = useId();
  async function emailSignIn(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const data = new FormData(event.currentTarget); const result = await authClient.signIn.email({ email: String(data.get("email")), password: String(data.get("password")), callbackURL: "/dashboard" }); if (result.error) setError(result.error.message ?? "Sign in failed."); }
  async function socialSignIn(provider: "github" | "google" | "microsoft") { setError(""); const result = await authClient.signIn.social({ provider, callbackURL: "/dashboard" }); if (result.error) setError(result.error.message ?? "Sign in failed."); }
  return <div className="grid gap-4">${email ? `<form className="grid gap-4" onSubmit={emailSignIn}><div className="grid gap-2"><Label htmlFor={emailId}>Email</Label><Input id={emailId} name="email" type="email" autoComplete="email" required /></div><div className="grid gap-2"><Label htmlFor={passwordId}>Password</Label><Input id={passwordId} name="password" type="password" autoComplete="current-password" minLength={8} required /></div><Button type="submit">Sign in</Button></form>` : ""}<div className="grid gap-2">${socialButtons}</div>{error ? <p role="alert" className="text-sm text-destructive">{error}</p> : null}</div>;
}
`;
  const files: Record<string, string> = {
    "lib/auth.ts": `import { betterAuth } from "better-auth/minimal";\n${imports}\nexport const auth = betterAuth({ appName: "${config.projectName}", baseURL: process.env.BETTER_AUTH_URL, database: ${database}, emailAndPassword: { enabled: ${email} }, socialProviders: { ${socialConfig} } });\n`,
    "lib/auth-client.ts": `"use client";\nimport { createAuthClient } from "better-auth/react";\nexport const authClient = createAuthClient();\n`,
    "lib/auth-session.ts": `import "server-only";\nimport { cache } from "react";\nimport { headers } from "next/headers";\nimport { redirect } from "next/navigation";\nimport { auth } from "@/lib/auth";\nexport const getSession = cache(async () => auth.api.getSession({ headers: await headers() }));\nexport async function requireSession() { const session = await getSession(); if (!session) redirect("/sign-in"); return session; }\n`,
    "app/api/auth/[...all]/route.ts": `import { toNextJsHandler } from "better-auth/next-js";\nimport { auth } from "@/lib/auth";\nexport const { GET, POST } = toNextJsHandler(auth);\n`,
    "components/auth/sign-in-form.tsx": form,
    "components/auth/sign-out-button.tsx": `"use client";\nimport { useRouter } from "next/navigation";\nimport { authClient } from "@/lib/auth-client";\nimport { Button } from "@/components/ui/button";\nexport function SignOutButton() { const router = useRouter(); async function signOut() { await authClient.signOut(); router.push("/sign-in"); router.refresh(); } return <Button type="button" variant="outline" onClick={() => void signOut()}>Sign out</Button>; }\n`,
    "app/sign-in/page.tsx": `import Link from "next/link";\nimport { Card } from "@/components/ui/card";\nimport { SignInForm } from "@/components/auth/sign-in-form";\nexport default function SignInPage() { return <main className="mx-auto grid min-h-dvh w-full max-w-md place-items-center px-6"><Card className="w-full p-6"><h1 className="text-2xl font-semibold">Sign in</h1><p className="mt-2 text-sm text-muted-foreground">Continue to ${config.projectName}.</p><div className="mt-6"><SignInForm /></div>${email ? `<p className="mt-5 text-sm text-muted-foreground">Need an account? <Link className="text-primary underline" href="/sign-up">Sign up</Link></p>` : ""}</Card></main>; }\n`,
    "app/dashboard/page.tsx": `import { SignOutButton } from "@/components/auth/sign-out-button";\nimport { requireSession } from "@/lib/auth-session";\nexport default async function DashboardPage() { const session = await requireSession(); return <main className="mx-auto min-h-dvh w-full max-w-5xl px-6 py-20"><div className="flex flex-wrap items-center justify-between gap-4"><p className="text-sm text-muted-foreground">Signed in as {session.user.email}</p><SignOutButton /></div><h1 className="mt-8 text-4xl font-semibold tracking-tight">Protected dashboard</h1><p className="mt-4 max-w-2xl text-muted-foreground">This page verifies the session on the server. Keep the same guard inside every protected Server Action and Route Handler.</p></main>; }\n`,
    "proxy.ts": `import { getSessionCookie } from "better-auth/cookies";\nimport { NextResponse, type NextRequest } from "next/server";\nexport function proxy(request: NextRequest) { if (!getSessionCookie(request)) return NextResponse.redirect(new URL("/sign-in", request.url)); return NextResponse.next(); }\nexport const config = { matcher: ["/dashboard/:path*"] };\n`,
  };
  if (email) {
    files["components/auth/sign-up-form.tsx"] = `"use client";\nimport { useId, useState, type FormEvent } from "react";\nimport { authClient } from "@/lib/auth-client";\nimport { Button } from "@/components/ui/button";\nimport { Input } from "@/components/ui/input";\nimport { Label } from "@/components/ui/label";\nexport function SignUpForm() { const [error, setError] = useState(""); const nameId = useId(); const emailId = useId(); const passwordId = useId(); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const data = new FormData(event.currentTarget); const result = await authClient.signUp.email({ name: String(data.get("name")), email: String(data.get("email")), password: String(data.get("password")), callbackURL: "/dashboard" }); if (result.error) setError(result.error.message ?? "Sign up failed."); } return <form className="grid gap-4" onSubmit={submit}><div className="grid gap-2"><Label htmlFor={nameId}>Name</Label><Input id={nameId} name="name" autoComplete="name" required /></div><div className="grid gap-2"><Label htmlFor={emailId}>Email</Label><Input id={emailId} name="email" type="email" autoComplete="email" required /></div><div className="grid gap-2"><Label htmlFor={passwordId}>Password</Label><Input id={passwordId} name="password" type="password" autoComplete="new-password" minLength={8} required /></div><Button type="submit">Create account</Button>{error ? <p role="alert" className="text-sm text-destructive">{error}</p> : null}</form>; }\n`;
    files["app/sign-up/page.tsx"] = `import Link from "next/link";\nimport { Card } from "@/components/ui/card";\nimport { SignUpForm } from "@/components/auth/sign-up-form";\nexport default function SignUpPage() { return <main className="mx-auto grid min-h-dvh w-full max-w-md place-items-center px-6"><Card className="w-full p-6"><h1 className="text-2xl font-semibold">Create an account</h1><p className="mt-2 text-sm text-muted-foreground">Start using ${config.projectName}.</p><div className="mt-6"><SignUpForm /></div><p className="mt-5 text-sm text-muted-foreground">Already registered? <Link className="text-primary underline" href="/sign-in">Sign in</Link></p></Card></main>; }\n`;
  }
  return files;
}

function renderCiFiles(config: StarterConfigV2): Record<string, string> {
  if (!config.ciEnabled) return {};
  const install = config.packageManager === "npm" ? "npm ci" : config.packageManager === "yarn" ? "yarn install --immutable" : `${config.packageManager} install --frozen-lockfile`;
  const run = `${config.packageManager} run verify`;
  const browser = config.testing.includes("playwright") ? `\n      - run: ${config.packageManager === "npm" ? "npx" : config.packageManager === "pnpm" ? "pnpm exec" : config.packageManager === "yarn" ? "yarn exec" : "bunx"} playwright install --with-deps chromium` : "";
  if (config.ci === "github-actions") {
    const setup = config.packageManager === "bun" ? "      - uses: oven-sh/setup-bun@v2\n" : `      - uses: actions/setup-node@v4\n        with:\n          node-version: 22\n${config.packageManager === "npm" ? "          cache: npm\n" : ""}${config.packageManager === "pnpm" ? `      - uses: pnpm/action-setup@v4\n        with:\n          version: 10.17.1\n` : ""}${config.packageManager === "yarn" ? "      - run: corepack enable\n" : ""}`;
    return { ".github/workflows/verify.yml": `name: Verify\non: [push, pull_request]\njobs:\n  verify:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n${setup}      - run: ${install}${browser}\n      - run: ${run}\n` };
  }
  const enable = config.packageManager === "bun" ? "npm install --global bun" : ["pnpm", "yarn"].includes(config.packageManager) ? "corepack enable" : "";
  const browserLine = config.testing.includes("playwright") ? `\n    - ${config.packageManager === "npm" ? "npx" : config.packageManager === "pnpm" ? "pnpm exec" : config.packageManager === "yarn" ? "yarn exec" : "bunx"} playwright install --with-deps chromium` : "";
  if (config.ci === "gitlab-ci") return { ".gitlab-ci.yml": `image: node:22\nverify:\n  script:\n${enable ? `    - ${enable}\n` : ""}    - ${install}${browserLine}\n    - ${run}\n` };
  return { "azure-pipelines.yml": `trigger:\n- main\npool:\n  vmImage: ubuntu-latest\nsteps:\n- task: NodeTool@0\n  inputs:\n    versionSpec: '22.x'\n${enable ? `- script: ${enable}\n` : ""}- script: ${install}${config.testing.includes("playwright") ? `\n- script: ${config.packageManager === "npm" ? "npx" : config.packageManager === "pnpm" ? "pnpm exec" : config.packageManager === "yarn" ? "yarn exec" : "bunx"} playwright install --with-deps chromium` : ""}\n- script: ${run}\n` };
}

export function renderWorkspaceFiles(config: StarterConfigV2): Record<string, string> {
  const dark = config.theme === "dark";
  const system = config.theme === "system";
  const font = renderFontSetup(config);
  const files: Record<string, string> = {
    "package.json": renderPackageJson(config),
    "README.md": renderReadme(config),
    ".gitignore": "node_modules\n.next\nout\n.vercel\n.env*\n!.env.example\ncoverage\nplaywright-report\ntest-results\n*.log\n*.tsbuildinfo\n.DS_Store\nlib/generated/prisma\n",
    ".env.example": renderEnvExample(config),
    "next-env.d.ts": "/// <reference types=\"next\" />\n/// <reference types=\"next/image-types/global\" />\n",
    "tsconfig.json": JSON.stringify({ compilerOptions: { target: "ES2022", lib: ["dom", "dom.iterable", "esnext"], allowJs: false, skipLibCheck: true, strict: true, noEmit: true, esModuleInterop: true, module: "esnext", moduleResolution: "bundler", resolveJsonModule: true, isolatedModules: true, jsx: "react-jsx", incremental: true, plugins: [{ name: "next" }], paths: { "@/*": ["./*"] } }, include: ["next-env.d.ts", ".next/types/**/*.ts", ".next/dev/types/**/*.ts", "**/*.ts", "**/*.tsx"], exclude: ["node_modules"] }, null, 2) + "\n",
    "postcss.config.mjs": "const config = { plugins: { '@tailwindcss/postcss': {} } };\nexport default config;\n",
    "components.json": JSON.stringify({ $schema: "https://ui.shadcn.com/schema.json", style: config.shadcnPreset.style, rsc: true, tsx: true, tailwind: { config: "", css: "app/globals.css", baseColor: config.shadcnPreset.baseColor, cssVariables: true }, iconLibrary: config.shadcnPreset.iconLibrary, aliases: { components: "@/components", utils: "@/lib/utils", ui: "@/components/ui", lib: "@/lib", hooks: "@/hooks" }, base: config.uiFoundation === "base-ui" ? "base-ui" : "radix" }, null, 2) + "\n",
    "lib/utils.ts": `import { clsx, type ClassValue } from "clsx";\nimport { twMerge } from "tailwind-merge";\nexport function cn(...inputs: ClassValue[]) { return twMerge(clsx(inputs)); }\n`,
    "components/ui/button.tsx": shadcnButton,
    "app/layout.tsx": `import type { Metadata } from "next";\n${font.imports}\nimport "./globals.css";\n${font.declarations}\nexport const metadata: Metadata = { title: "${config.projectName}", description: "Generated from an agent-ready application blueprint." };\nexport default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) { return <html lang="en" className={\`${font.classes}${dark ? " dark" : ""}\`}><body>{children}</body></html>; }\n`,
    "app/page.tsx": renderHome(config),
    "app/globals.css": `@import "tailwindcss";\n@custom-variant dark (&:is(.dark *));\n:root { color-scheme: ${system ? "light dark" : dark ? "dark" : "light"}; --background: ${dark ? "oklch(0.12 0.006 285)" : "oklch(0.985 0.003 285)"}; --foreground: ${dark ? "oklch(0.96 0.004 286)" : "oklch(0.16 0.006 285)"}; --card: ${dark ? "oklch(0.17 0.007 285)" : "oklch(1 0 0)"}; --card-foreground: var(--foreground); --primary: ${presetAccent[config.shadcnPreset.theme]}; --primary-foreground: oklch(0.99 0 0); --muted: ${dark ? "oklch(0.2 0.008 285)" : "oklch(0.94 0.005 285)"}; --muted-foreground: ${dark ? "oklch(0.7 0.012 285)" : "oklch(0.46 0.01 285)"}; --accent: var(--muted); --destructive: oklch(0.62 0.21 25); --border: ${dark ? "oklch(0.27 0.01 285)" : "oklch(0.88 0.006 285)"}; --input: var(--border); --ring: var(--primary); --radius: ${presetRadius[config.shadcnPreset.radius]}; }${system ? `\n@media (prefers-color-scheme: dark) { :root { --background: oklch(0.12 0.006 285); --foreground: oklch(0.96 0.004 286); --card: oklch(0.17 0.007 285); --muted: oklch(0.2 0.008 285); --muted-foreground: oklch(0.7 0.012 285); --border: oklch(0.27 0.01 285); } }` : ""}\n@theme inline { --font-sans: var(--font-preset-sans), ui-sans-serif, system-ui, sans-serif; --font-mono: var(--font-preset-mono), ui-monospace, monospace; --color-background: var(--background); --color-foreground: var(--foreground); --color-card: var(--card); --color-card-foreground: var(--card-foreground); --color-primary: var(--primary); --color-primary-foreground: var(--primary-foreground); --color-muted: var(--muted); --color-muted-foreground: var(--muted-foreground); --color-accent: var(--accent); --color-destructive: var(--destructive); --color-border: var(--border); --color-input: var(--input); --color-ring: var(--ring); --radius-sm: calc(var(--radius) * .75); --radius-md: calc(var(--radius) * .875); --radius-lg: var(--radius); }\n* { border-color: var(--border); box-sizing: border-box; }\nbody { margin: 0; min-height: 100dvh; background: var(--background); color: var(--foreground); font-family: var(--font-sans); }${font.headingCss}\n:focus-visible { outline: 2px solid var(--ring); outline-offset: 3px; }\n@media (prefers-reduced-motion: reduce) { *, *::before, *::after { animation-duration: .01ms !important; animation-iteration-count: 1 !important; scroll-behavior: auto !important; transition-duration: .01ms !important; } }\n`,
    ...renderDatabaseFiles(config),
    ...renderAuthFiles(config),
    ...renderCiFiles(config),
  };
  Object.assign(files, { "components/ui/card.tsx": shadcnFields["components/ui/card.tsx"] });
  if (config.authentication === "better-auth") Object.assign(files, shadcnFields);
  if (config.tooling === "biome") files["biome.json"] = JSON.stringify({ $schema: "https://biomejs.dev/schemas/2.2.4/schema.json", vcs: { enabled: true, clientKind: "git", useIgnoreFile: true }, files: { includes: ["**", "!!.next", "!!lib/generated/prisma"] }, formatter: { enabled: true, indentStyle: "space" }, linter: { enabled: true, rules: { recommended: true, suspicious: { noUnknownAtRules: "off" }, complexity: { noImportantStyles: "off" }, a11y: { noLabelWithoutControl: "off" } } }, javascript: { formatter: { quoteStyle: "double", semicolons: "always" } } }, null, 2) + "\n";
  else {
    files["eslint.config.mjs"] = `import { defineConfig, globalIgnores } from "eslint/config";\nimport nextVitals from "eslint-config-next/core-web-vitals";\nimport nextTypeScript from "eslint-config-next/typescript";\nimport prettier from "eslint-config-prettier/flat";\nexport default defineConfig([...nextVitals, ...nextTypeScript, prettier, globalIgnores([".next/**", "lib/generated/prisma/**"])]);\n`;
    files["prettier.config.mjs"] = `const config = { semi: true, singleQuote: false, trailingComma: "all" };\nexport default config;\n`;
    files[".prettierignore"] = ".next\nDESIGN.md\nlib/generated/prisma\nplaywright-report\ntest-results\n";
  }
  if (config.testing.includes("vitest")) {
    files["vitest.config.ts"] = `import react from "@vitejs/plugin-react";\nimport { defineConfig } from "vitest/config";\nexport default defineConfig({ plugins: [react()], test: { environment: "jsdom", include: ["tests/**/*.test.{ts,tsx}"], setupFiles: ["./tests/setup.ts"] }, resolve: { alias: { "@": new URL(".", import.meta.url).pathname } } });\n`;
    files["tests/setup.ts"] = `import "@testing-library/jest-dom/vitest";\n`;
    files["tests/home.test.tsx"] = `import { render, screen } from "@testing-library/react";\nimport { describe, expect, it } from "vitest";\nimport Home from "@/app/page";\ndescribe("home", () => { it("renders the generated project name", () => { render(<Home />); expect(screen.getByRole("heading", { name: /Ready to build ${config.projectName}/i })).toBeInTheDocument(); }); });\n`;
  }
  if (config.testing.includes("playwright")) {
    const nextDev = config.packageManager === "npm" ? "npx next dev --port 3107" : config.packageManager === "pnpm" ? "pnpm exec next dev --port 3107" : config.packageManager === "yarn" ? "yarn exec next dev --port 3107" : "bunx next dev --port 3107";
    files["playwright.config.ts"] = `import { defineConfig, devices } from "@playwright/test";\nexport default defineConfig({ testDir: "./tests/e2e", webServer: { command: "${nextDev}", url: "http://localhost:3107", reuseExistingServer: !process.env.CI }, use: { baseURL: "http://localhost:3107", trace: "on-first-retry" }, projects: [{ name: "chromium", use: { ...devices["Desktop Chrome"] } }] });\n`;
    files["tests/e2e/home.spec.ts"] = `import { expect, test } from "@playwright/test";\ntest("starter renders", async ({ page }) => { await page.goto("/"); await expect(page.getByRole("heading", { name: /Ready to build/i })).toBeVisible(); });\n`;
  }
  const otel = config.observability.includes("opentelemetry");
  const sentry = config.observability.includes("sentry");
  if (otel || sentry) {
    const imports = `${otel ? `import { registerOTel } from "@vercel/otel";\n` : ""}${sentry ? `import * as Sentry from "@sentry/nextjs";\n` : ""}`;
    const sentryRegistration = sentry ? `  if (process.env.NEXT_RUNTIME === "nodejs") await import("./sentry.server.config");\n  if (process.env.NEXT_RUNTIME === "edge") await import("./sentry.edge.config");\n` : "";
    files["instrumentation.ts"] = `${imports}export async function register() {\n${otel ? `  registerOTel({ serviceName: "${config.projectName}" });\n` : ""}${sentryRegistration}}\n${sentry ? `export const onRequestError = Sentry.captureRequestError;\n` : ""}`;
  }
  if (sentry) {
    const sentryInit = `import * as Sentry from "@sentry/nextjs";\nSentry.init({ dsn: process.env.NEXT_PUBLIC_SENTRY_DSN, tracesSampleRate: process.env.NODE_ENV === "development" ? 1 : 0.1 });\n`;
    files["sentry.server.config.ts"] = sentryInit;
    files["sentry.edge.config.ts"] = sentryInit;
    files["instrumentation-client.ts"] = `${sentryInit}export const onRouterTransitionStart = Sentry.captureRouterTransitionStart;\n`;
    files["next.config.ts"] = `import type { NextConfig } from "next";\nimport { withSentryConfig } from "@sentry/nextjs";\nconst nextConfig: NextConfig = {};\nexport default withSentryConfig(nextConfig, { org: process.env.SENTRY_ORG, project: process.env.SENTRY_PROJECT, authToken: process.env.SENTRY_AUTH_TOKEN, silent: !process.env.CI });\n`;
    files["app/global-error.tsx"] = `"use client";\nimport * as Sentry from "@sentry/nextjs";\nimport NextError from "next/error";\nimport { useEffect } from "react";\nexport default function GlobalError({ error }: { error: Error & { digest?: string } }) { useEffect(() => { Sentry.captureException(error); }, [error]); return <html lang="en"><body><NextError statusCode={0} /></body></html>; }\n`;
  }
  return files;
}
